Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -45,11 +45,23 @@ runs:
       shell: bash
       if: ${{ success() }}
 
-    - name: Start main application inside container
-      run: docker exec kexadockeractioncontainer pnpm run start:nobuild
-      shell: bash
-      if: ${{ success() }}
+#    - name: Start main application inside container
+#      run: docker exec kexadockeractioncontainer pnpm run start:nobuild
+#      shell: bash
+#      if: ${{ success() }}
 
+    - name: Start main application inside container
+      run: |
+        docker exec kexadockeractioncontainer sh -c '
+          pnpm run start:nobuild
+          EXIT_CODE=$?
+          echo "Exit code: $EXIT_CODE"
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "pnpm run start:nobuild failed with exit code $EXIT_CODE"
+            exit $EXIT_CODE
+          fi
+        '
+      shell: bash
 #
 #    - name: Check if Docker run failed
 #      if: ${{ always() }}
