Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -157,46 +157,46 @@ runs:
         fi
       shell: bash
 
-    - name: Multiple workspace credentials, create files and set env variables
-      if: steps.check_workspacecred.outputs.exists == 'false'
-      run: |
-        echo "checking for multiple workspace credentials"
+    # - name: Multiple workspace credentials, create files and set env variables
+    #   if: steps.check_workspacecred.outputs.exists == 'false'
+    #   run: |
+    #     echo "checking for multiple workspace credentials"
 
-        if [ -z "${{ inputs.WORKSPACECRED_PREFIX }}" ]; then
-          echo "WORKSPACECRED_PREFIX not found."
-          exit 0
-        fi
+    #     if [ -z "${{ inputs.WORKSPACECRED_PREFIX }}" ]; then
+    #       echo "WORKSPACECRED_PREFIX not found."
+    #       exit 0
+    #     fi
 
-        echo "WORKSPACECRED_PREFIX found for multiple conf."
+    #     echo "WORKSPACECRED_PREFIX found for multiple conf."
 
-        WORKSPACEPREFIXES="${{ inputs.WORKSPACECRED_PREFIX }}"
-        IFS=',' read -r -a workspace_prefixes <<< "$WORKSPACEPREFIXES"
+    #     WORKSPACEPREFIXES="${{ inputs.WORKSPACECRED_PREFIX }}"
+    #     IFS=',' read -r -a workspace_prefixes <<< "$WORKSPACEPREFIXES"
 
-        if [ ${#workspace_prefixes[@]} -gt 0 ]; then
-          for idx in "${!workspace_prefixes[@]}"; do
-            prefix="${workspace_prefixes[$idx]}"
+    #     if [ ${#workspace_prefixes[@]} -gt 0 ]; then
+    #       for idx in "${!workspace_prefixes[@]}"; do
+    #         prefix="${workspace_prefixes[$idx]}"
 
-            INPUT_PREFIX_WORKSPACE="${prefix}WORKSPACECRED"
+    #         INPUT_PREFIX_WORKSPACE="${prefix}WORKSPACECRED"
 
-            newInputs='${{ toJson(inputs) }}'
-            workspace=""
-            for key in $(echo "$newInputs" | jq -r 'keys[]'); do
-              value=$(echo "$newInputs" | jq -r ".\"$key\"")
-              if [ "$key" == "$INPUT_PREFIX_WORKSPACE" ]; then
-                workspace="${value}"
-              fi
-            done
+    #         newInputs='${{ toJson(inputs) }}'
+    #         workspace=""
+    #         for key in $(echo "$newInputs" | jq -r 'keys[]'); do
+    #           value=$(echo "$newInputs" | jq -r ".\"$key\"")
+    #           if [ "$key" == "$INPUT_PREFIX_WORKSPACE" ]; then
+    #             workspace="${value}"
+    #           fi
+    #         done
 
-            echo "${workspace}" > "workspace_${idx}.json"
+    #         echo "${workspace}" > "workspace_${idx}.json"
 
-            echo "${prefix}WORKSPACECRED=/app/config/workspace_${idx}.json" >> .env
-            chmod 700 "workspace_${idx}.json"
-          done
-        else
-          echo "No WORKSPACECRED_PREFIX values found."
-          exit 1
-        fi
-      shell: bash
+    #         echo "${prefix}WORKSPACECRED=/app/config/workspace_${idx}.json" >> .env
+    #         chmod 700 "workspace_${idx}.json"
+    #       done
+    #     else
+    #       echo "No WORKSPACECRED_PREFIX values found."
+    #       exit 1
+    #     fi
+    #   shell: bash
 
     
 
