Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -79,6 +79,11 @@ runs:
       id: check_kubeconfig_multiple
       if: steps.check_kubeconfig.outputs.exists == 'false'
       run: |
+        if [ -z "${{ inputs.KUBEPREFIX }}" ]; then
+          echo "KUBEPREFIX not found."
+          exit 1
+        fi
+
         KUBEPREFIXES="${{ inputs.KUBEPREFIX }}"
         IFS=',' read -r -a kubeprefixes <<< "$KUBEPREFIXES"
 
@@ -132,6 +137,11 @@ runs:
     - name: Multiple workspace credentials, create files and set env variables
       if: steps.check_workspacecred.outputs.exists == 'false'
       run: |
+        if [ -z "${{ inputs.WORKSPACEPREFIX }}" ]; then
+          echo "WORKSPACEPREFIX not found."
+          exit 1
+        fi
+        
         WORKSPACEPREFIXES="${{ inputs.WORKSPACEPREFIX }}"
         IFS=',' read -r -a workspaceprefixes <<< "$WORKSPACEPREFIXES"
 
@@ -160,7 +170,7 @@ runs:
         fi
       shell: bash
 
-      
+
     ############
     #   GCP    #
     ############
@@ -183,6 +193,11 @@ runs:
     - name: Multiple google application credentials, create files and set env variables
       if: steps.check_google_application_credentials.outputs.exists == 'false'
       run: |
+        if [ -z "${{ inputs.GOOGLE_APPLICATION_CREDENTIALS_PREFIX }}" ]; then
+          echo "GOOGLE_APPLICATION_CREDENTIALS_PREFIX not found."
+          exit 1
+        fi
+        
         GOOGLE_APPLICATION_CREDENTIALS_PREFIXES="${{ inputs.GOOGLE_APPLICATION_CREDENTIALS_PREFIX }}"
         IFS=',' read -r -a google_application_credentials_prefixes <<< "$GOOGLE_APPLICATION_CREDENTIALS_PREFIXES"
 
