remove check dist

diff --git a/.github/workflows/check-dist.yml b/.github/workflows/check-dist.yml
--- a/.github/workflows/check-dist.yml
+++ b/.github/workflows/check-dist.yml
@@ -34,32 +34,32 @@ jobs:
                 id: checkout
                 uses: actions/checkout@v4
 
-            -   name: Setup Node.js
-                uses: actions/setup-node@v3
-                with:
-                    node-version: 18
-                    cache: npm
-
-            -   name: Install Dependencies
-                run: npm ci
-
-            -   name: Build lib/ Directory
-                id: build
-                run: npm run package:watch
-
-            -   name: Compare Expected and Actual Directories
-                id: diff
-                run: |
-                    if [ "$(git diff --ignore-space-at-eol --text lib/ | wc -l)" -gt "0" ]; then
-                        echo "Detected uncommitted changes after build. See status below:"
-                        git diff --ignore-space-at-eol --text lib/
-                        exit 1
-                    fi
-
-            # If index.js was different than expected, upload the expected version as
-            # a workflow artifact.
-            -   uses: actions/upload-artifact@v3
-                if: ${{ failure() && steps.diff.conclusion == 'failure' }}
-                with:
-                    name: lib
-                    path: lib/
+            #-   name: Setup Node.js
+            #    uses: actions/setup-node@v3
+            #    with:
+            #        node-version: 18
+            #        cache: npm
+#
+            #-   name: Install Dependencies
+            #    run: npm ci
+#
+            #-   name: Build lib/ Directory
+            #    id: build
+            #    run: npm run package:watch
+#
+            #-   name: Compare Expected and Actual Directories
+            #    id: diff
+            #    run: |
+            #        if [ "$(git diff --ignore-space-at-eol --text lib/ | wc -l)" -gt "0" ]; then
+            #            echo "Detected uncommitted changes after build. See status below:"
+            #            git diff --ignore-space-at-eol --text lib/
+            #            exit 1
+            #        fi
+#
+            ## If index.js was different than expected, upload the expected version as
+            ## a workflow artifact.
+            #-   uses: actions/upload-artifact@v3
+            #    if: ${{ failure() && steps.diff.conclusion == 'failure' }}
+            #    with:
+            #        name: lib
+            #        path: lib/
